name: PHP CI

on:
    - push
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install
              run: make install

            - name: Run Lint
              run: make lint

            - name: Run PHPStan
              run: make analyse

            - name: Run Tests
              run: make test
